### ISSUE TITLE
Add events?

### ISSUE THREAD

**Issue by garak** [fazland/skebby-rest-client#11]
What about dispatching an event after sms sending?
We could easily inject an optional `Psr\EventDispatcher\EventDispatcherInterface.php` object to `Client` constructor.
If object is not null, we could dispatch an event with useful information (recipient, content, response).
This can be back-compatible: if object is null, we can just ignore it.

**Comment by massimilianobraglia** [comment]
Hey there, @garak! Sounds good to me, interesting feature. Can you  make a PR for this one?

**Comment by garak** [comment]
Of course, I'll do it in the next days

**Comment by massimilianobraglia** [comment]
Thank you 😄 🚀
