### ISSUE TITLE
Raise PHP minimum version

### ISSUE THREAD

**Issue by alekitto** [fazland/skebby-rest-client#13]
PHP 7.0 is EOL two years ago.
My proposal is to raise the minimum supported PHP version to 7.4.

**Comment by garak** [comment]
I wouldn't drop 7.3, since it's still in "Security fixes only" (so, it's somehow supported)

**Comment by garak** [comment]
Additionally, I would drop any symfony component before 4.4

**Comment by alekitto** [comment]
7.3 will be EOL'd in a few months, I'd prefer to set the supported versions to one that has a life longer than one year.
What about a release (0.3.0) without changing the supported php versions and >= 7.4 on `master`?

**Comment by garak** [comment]
> 7.3 will be EOL'd in a few months, I'd prefer to set the supported versions to one that has a life longer than one year.
> What about a release (0.3.0) without changing the supported php versions and >= 7.4 on `master`?

It's OK for me.
I would go with `^7.4 || ^8.0` instead of `>= 7.4`, it's more cautious about future php versions.
