### ISSUE TITLE
New Skebby APIs

### ISSUE THREAD

**Issue by opicodes** [fazland/skebby-rest-client#17]
Skebby has updated their APIs and [here](https://www.skebby.it/business/index/send-docs/) they suggest updating.

In particular I noticed the **_send_** endpoint has a different address and a different set of **_Body parameters_** https://developers.skebby.it/?&_ga=2.184476965.2044171531.1622816656-409620249.1622565132#send-an-sms-message

[Here's the link to their docs](https://developers.skebby.it/?&_ga=2.184476965.2044171531.1622816656-409620249.1622565132#skebby-rest-api-introduction)

**Comment by massimilianobraglia** [comment]
Hey there @opicodes! Thank you for this issue. Can you submit a PR in order to support the new API?

**Comment by alekitto** [comment]
Hi @opicodes,
I saw that the API completely changed in this new version. Probably we need to open a roadmap issue to coordinate the development of a new version of this SDK. I'll open it in a few hours.

**Comment by alekitto** [comment]
I've opened an issue containing a proposal for a roadmap to implement the new APIs (#18).
Please share any thoughts about it in that issue. I'm closing this for now, feel free to re-open it if needed.
