### ISSUE TITLE
Add NullTransport

### ISSUE THREAD

**Issue by garak** [fazland/skebby-rest-client#9]
What about adding a `NullTransport`? It would be an implementation of `TransportInterface` where `executeRequest` is just doing nothing (more or less like in Swiftmailer for emails).
It could be useful in dev/test environments.
I can provide a PR.

**Comment by massimilianobraglia** [comment]
Hey @garak, that's quite a good idea. Unfortunately I'm a bit busy at the moment so if you can provide a PR I will be happy to review it!
